package com.app.model.api.constants

object ApiEndPoints {
    const val SEND_OTP = "Account/Login2SendOtp2"
    const val SEND_MOBILE_OTP = "Utility/SendOtp2"
    const val VERIFY_OTP = "Account/Login2Access"
    const val EXTRACT_QID = "Utility/ExtractQid"
    const val LOGIN = "Account/Login"
    const val REGISTER = "Member/AddUser"
    const val REGISTER_UNKNOWN_USER = "Member/AddUser1"
    const val REGISTER_TICKET_USER = "Member/AddUser2"
    const val REGISTER_NONE_QATARI_USER = "Member/AddUser3"
    const val GET_TICKET = "Ticket/GetUserTickets"
    const val GET_TICKET_CONFIG = "Ticket/GetTicketConfig"
    const val GET_TICKET_DATA = "Ticket/GetBookingDatesAtimeSlots"
    const val BOOK_TICKET = "Ticket/AddUserTicket"
    const val GET_NEWS = "News/GetNews"
    const val GET_BANNER = "Banner/GetBanners"
    const val GET_FALCON = "Falcon/GetListFalcon2ByCategory"
    const val CHECK_QID = "Member/UserQidExist2"
    const val GET_FALCON_CATEGORY = "Falcon/GetListFalconCategory"
    const val GET_AUCTION_EXPIRED = "Falcon/GetListFalcon2Expired"
    const val GET_AUCTION_10 = "Aucction/GetTop10"
    const val GET_AUCTION_LAST_BET = "Aucction/LastBet"
    const val GET_AUCTION_DETAILS = "Falcon/GetFalcon"
    const val GET_AUCTION_PREVIOUS_DETAILS = "Falcon/GetExpiredFalcon"
    const val GET_AUCTION_MAX_PRICE = "Aucction/FalconMaxPrice"
    const val GET_AUCTION_MAKE_BET = "Aucction/MakeBet"
    const val REFRESH_USER = "Account/RefreshUser"
    const val FORCE_UPDATE = "Utility/GetAppUpdate"
    const val PRODUCT = "Shop/GetListBestProduct"
    const val SHOP = "Shop/GetListShop"
    const val SHOP_DETAILS = "Shop/GetShopDetails"
    const val GET_ISD = "Utility/GetIsd"
    const val GET_COUNTRIES= "Utility/GetContry"
    const val GET_AUCTION_IS_FOR_QATARI= "Utility/AuctionIsForQatari"
    const val REQUEST_ACCOUNT_UPGRADE= "Member/RequesttAccountUpgrade"

}